### PR TITLE
Add exit icon

### PR DESCRIPTION
**Pull request by ianchobuilds**
- Add exit icon due to RidiSelect settings page

### CODE REVIEW

**Comment by ianchobuilds** [comment]
@incleaf Could you also publish the package after merging?

**Review by incleaf — APPROVED** [review]

**Comment by incleaf** [comment]
@gyujincho I actually don't have permission on npm 😅

**Comment by incleaf** [comment]
@J132134 will publish it soon!

**Comment by namenu** [comment]
FYI, @krazijames is also an administrator.

**Pull request merged**
